version: "3.8"
services:
  message-broker:
    image: rabbitmq:3.12.10
    ports:
      - "5672:5672"
      - "15672:15672"
  service-discovery:
    build: ./service-discovery
    ports:
      - "8761:8761"
  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - "4566:4566"
    restart: always
  resource-service:
    build: service-resource
    ports:
      - "8080:8080"
    restart: always
    environment:
      - DATABASE_PASSWORD=${PASSWORD}
      - DATABASE_URL=jdbc:postgresql://resources-db:5432/${RESOURCE_DB}
      - DATABASE_USER=${USER}
      - EUREKA_CLIENT_URL=${SERVICE_DISCOVERY_URL}
    depends_on:
      - resources-db
      - localstack
      - songs-service
      - service-discovery
  songs-service:
    build: service-song
    expose:
      - "8080"
    deploy:
      mode: replicated
      replicas: 3
    restart: always
    environment:
      - DATABASE_PASSWORD=${PASSWORD}
      - DATABASE_URL=jdbc:postgresql://songs-db:5432/${SONGS_DB}
      - DATABASE_USER=${USER}
      - EUREKA_CLIENT_URL=${SERVICE_DISCOVERY_URL}
    depends_on:
      - songs-db
      - service-discovery
  resources-db:
    image: "postgres:16-alpine"
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${RESOURCE_DB}
      - POSTGRES_USER=${USER}
    ports:
      - "7001:5432"
    restart: always
    volumes:
      - /resources-db:/var/lib/postgresql/data
  songs-db:
    image: "postgres:16-alpine"
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${SONGS_DB}
      - POSTGRES_USER=${USER}
    ports:
      - "7002:5432"
    restart: always
    volumes:
      - /songs-db:/var/lib/postgresql/data
  service-charlie:
    build: ./service-charlie
    expose:
      - "8080"
    restart: always
    depends_on:
      - message-broker