version: "3.8"
services:
  resource-service:
    build: service-resource
    ports:
      - "8080:8080"
    depends_on:
      - resources-db
  songs-service:
    build: service-song
    ports:
      - "8081:8080"
    depends_on:
      - songs-db
  resources-db:
    image: "postgres:16-alpine"
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${RESOURCE_DB}
    ports:
      - "7001:5432"
    volumes:
      - /resources-db:/var/lib/postgresql/data
  songs-db:
    image: "postgres:16-alpine"
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${SONGS_DB}
    ports:
      - "7002:5432"
    volumes:
      - /songs-db:/var/lib/postgresql/data