spring:
  application:
    name: resource-service
  rabbitmq:
    host: message-broker
    username: guest
    password: guest
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
     ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet.multipart.max-file-size: 10MB
  servlet.multipart.max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_URL}
my:
  client:
    audio:
     id: SONGS-SERVICE
     endpoint: songs
    s3:
     url: http://localstack:4566
     accessKey: fake_access_key
     secretKey: fake_secret_key
     bucket: com.tsarankou.my
     region: us-west-1
broker:
  resource:
    createResourceRouting: create.resource.#
    resourceTopic: create-resource-topic
    deleteResourceQueue: delete.resource.#
