spring:
  rabbitmq:
    host: message-broker
    username: guest
    password: guest
my:
  client:
    resource:
      schema: http
      host: resource-service
      port: 8080
      endpoint: resources
    songs:
      id: SONGS-SERVICE
      endpoint: songs
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
