spring:
  application:
    name: resource-processor
  rabbitmq:
    host: message-broker
    username: guest
    password: guest
  codec:
    max-in-memory-size: 10MB
my:
  client:
    resource:
      schema: http
      host: resource-service
      port: 8080
      endpoint: resources
    audio:
      id: SONGS-SERVICE
      endpoint: songs
server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_URL}
broker:
    resource:
      createQueue: queue-create-resource
      topic: create-resource-topic
      createRouting: create.resource.#
